# Generated by Django 3.1.5 on 2021-08-02 17:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('father_name', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pin', models.TextField()),
                ('mobile_number', models.TextField(unique=True)),
                ('email', models.TextField(unique=True)),
                ('class_opt', models.PositiveSmallIntegerField(choices=[(5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth'), (9, 'Ninth')], default=5)),
                ('marks', models.FloatField()),
                ('date_enrolled', models.DateTimeField(default=datetime.datetime(2021, 8, 2, 17, 18, 15, 263210, tzinfo=utc))),
            ],
        ),
    ]
